### ISSUE TITLE
RBPI unreacheable

### ISSUE THREAD

**Issue by hellosarobotics** [wildfoundry/dataplicity-agent#56]
Hello,
I've have a rasbperry pi behind a 4g router.
It sends me data to my server, so there is internet connection, but, the rbpi is not reacheable by dataplicity...
Why?
My Server show the green button status
![Selection_160](https://user-images.githubusercontent.com/37176642/55331967-b203d780-5494-11e9-85d5-298c14e897fd.png)

Dataplicity account
![Selection_158](https://user-images.githubusercontent.com/37176642/55331804-5df8f300-5494-11e9-900c-8df47b794148.png)

**Comment by Radoslaw-K** [comment]
Hey,

Thank you for reporting the issue you have with your device. 
We'd love to take a look at what the problem is. Are you able to physically access the device ? If you do, something you could try to bring the device back online is running command:
​
​sudo supervisorctl restart tuxtunnel 
​
Furthermore, to try and figure out the reason for the problem please run:
​
​curl https://www.dataplicity.com/diagnostics.py | sudo python​

and send us the code that this will return at the end. 

Could you contact us on our live chat "intercom" with a response to this message please?
​
Best,
Radoslaw

**Comment by hellosarobotics** [comment]
Ok,
after restart, the rbpi is reacheable.
Next time the status is red, I will send you the result of:
curl https://www.dataplicity.com/diagnostics.py | sudo python​
Thank you very much.
