### ISSUE TITLE
Home Assistant & Dataplicity

### ISSUE THREAD

**Issue by jonach66** [wildfoundry/dataplicity-agent#89]
Hi All,

I´m using Home Assistant (HA) 2023.1.1 & Dataplicity (DP), but with the latest HA upgrades I run into an dependency issue:
- to work properly HA needs six==1.16.0, otherwise e.g. USB ports not working
- the DP custom component (based on DP 0.40.x) version for HA needs six==1.10.0, otherwise it will not be loaded in HA Core environment

Rasbian Bullseye, Python 3.10.9, HA Core Version in an VENV environment...

Any hints, any chance to get this fixed?

Kind regards!
Jo

**Comment by GregorD1A1** [comment]
Hello @jonach66 !

In fact, as Dataplicity we have no impact on that, as the DP custom component is an unofficial integration, written by someone else. Here I can recommend you two things:
1. Ask https://github.com/AlexxIT/Dataplicity if he can update DP custom component to It will be compatible with six==1.16.0 (I see you already did it).
2. Try to install HA image as an operating system on your SD card instead of Raspbian. Most of the users use HA as the whole operating system and I had no any reports from them last time, so that way DP custom component should still work.

Best Regards,
Grigorij

**Comment by GregorD1A1** [comment]
@jonach66 I'm trying to recreate your problem now to maybe create a patch for AlexxIt's DP custom component. I installed HA core version in my raspbian in venv environment (checked six's version, it was 1.16.0), after that installed HACS and installed DP custom component through the HACS. Now DP custom component works just fine for me.

Maybe I'm doing something different?

**Comment by jonach66** [comment]
Hi Grigorij,

thank you for your advice. I had some "artefacts" installed, old supervisor & dataplicity agent which caused this dependency issues. Uninstalled them, problem solved!

Very very sorry for bothering you!!

Kind regards!
Josef
